name: repository-dispatch

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [example-dispatch-event]

jobs:
  error-job:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      error: ${{ steps.error.outputs.error }}
    steps:
      - id: error
        name: error
        run: |
          echo "github.event.type: ${{ github.event.type }}"
          echo "This is an example error"
          echo "error=true" >> $GITHUB_OUTPUT
          exit 1
  example-job:
    if: ${{ always() && (needs.error-job.outputs.error == 'true' || github.event.action == 'example-dispatch-event') }}
    needs: [error-job]
    runs-on: ubuntu-latest
    steps:
      - name: log-event
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Event client payload: ${{ toJson(github.event.client_payload) }}"
