name: repository-dispatch

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [example-dispatch-event]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'example-dispatch-event' }}
    steps:
      - id: echo
        name: echo
        run: |
          echo "github.event.type: ${{ github.event.type }}"
          echo "This is an example job"
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "randomizer failed"
            exit 1
          fi
  example-job:
    if: ${{ always() && (needs.echo-job.result != 'skipped' || github.event.action == 'example-dispatch-event') }}
    needs: [echo-job]
    runs-on: ubuntu-latest
    steps:
      - name: log-event
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Event client payload: ${{ toJson(github.event.client_payload) }}"
